### ISSUE TITLE
definition files not contained in chart

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#133]
When oam-k8s-runtime installed, we will have manualscaler trait, containerizedworkload, health scope.

But now, their definition files are not contained in chart, which means we can't use them.

We should put definition file of these controller into charts.

* health scope[ definition file](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/containerized-workload/sample_scope_definition.yaml)
* manualscaler [definition file](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/containerized-workload/sample_trait_definition.yaml)
* containerized workload [definition file](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/containerized-workload/sample_workload_definition.yaml)

**Comment by SataQiu** [comment]
Hi @wonderflow !
Emm...  I found it is a little hard to put these `definition files` into the `crds` folder for automatic installation:
1. the `definition file` is CR, `crds` folder should store CRD instead of CR
2. we cannot guarantee that the creation of a CR is later than the creation of it's CRD

Do we want to put these definition files into the `templates` folder ? But I think it will cause an error if we pass `--skip-crds` flag when running `helm install` :sweat_smile:

**Comment by wonderflow** [comment]
> Do we want to put these definition files into the `templates` folder ?

Yes.

You can assume our users are using helm v3 and won't use `--skip-crds` flags.

**Comment by wonderflow** [comment]
Hi @SataQiu , are you still working on this?

**Comment by wonderflow** [comment]
I'm going to take it since this issue hurt user experience a lot, sorry @SataQiu
