### ISSUE TITLE
[proposal]Generic Trait Interface

### ISSUE THREAD

**Issue by FingerLiu** [crossplane/oam-kubernetes-runtime#39]
I saw the core types, like ManualScalerTrait, it is too specific, and we can not reuse things from it, and we can not ensure user written traits works like we assume.
So I think it would be great if we can define a Generic Trait Interface, which define basic attribute and method, such as `WorkloadRed`, `Apply`.
Would this be possible?

**Comment by ryanzhang-oss** [comment]
I wonder if you can explain a bit on why do you think a ManualScalerTrait is "too specific"? What exactly does a `WorkloadRed` or a `Apply` trait should do?

**Comment by FingerLiu** [comment]
我表达的可能不太清楚，比如我想实现一个自己的 Trait，我在实现这个 Trait 的时候，应该怎么实现呢

我期望的可能是有一个 TraitInterface , 里面告诉了我实现了哪些方法，就可以实现自己的 Trait 和自己的 Trait controller，且可以配给 component 使用。

还是说我的打开方式不对？

**Comment by wonderflow** [comment]
I think we need to know more about your use case instead of telling how to write a generic trait.

@FingerLiu  I send you an email, we can contact offline.

**Comment by wonderflow** [comment]
I discussed with @FingerLiu and explained [the workload and trait mechanism](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/one-pager-trait-workload-interaction-mechanism.md).  This issue seems to be more important now https://github.com/crossplane/oam-kubernetes-runtime/issues/38

**Comment by resouer** [comment]
I think  the Trait lib we discussed before is what's needed here.
